<?php

namespace Magelearnnew\ProductColumnCatlog\Ui\Component\Listing\Column;

use Magento\Catalog\Model\CategoryFactory;
use Magento\Catalog\Model\ProductRepository;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class Category extends Column
{


    /**
     * @var ProductRepository
     */
    private $productRepository;

    /** @var CategoryFactory  */
    private $categoryFactory;

    /**
     * @param ContextInterface $context
     * @param UiComponentFactory $uiComponentFactory
     * @param ProductRepository $productRepository
     * @param CategoryFactory $categoryFactory
     * @param array $components
     * @param array $data
     */
    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        ProductRepository $productRepository,
        CategoryFactory $categoryFactory,
        array $components = [],
        array $data = []
    )
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->productRepository = $productRepository;
        $this->categoryFactory = $categoryFactory;
    }

    public function prepareDataSource(array $dataSource)
    {
        if(isset($dataSource['data']['items'])){
            $fieldName = $this->getData('name');

            foreach ($dataSource['data']['items'] as & $item){
                $productId = $item['entity_id'];

            }
        }
        return $dataSource; // TODO: Change the autogenerated stub
    }


}
